import type { Metadata } from "next";

import "./globals.css";
import Provider from "./providers";



export const metadata: Metadata = {
  title: "convertprice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Provider>
        
        {children}
        
      </Provider>
        </body>

    </html>
  );
}
